modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="davidscreativetools"
version="1.0.0"
displayName="David's Creative Tools"
description='''Creative tools for advanced control.'''
